### PR TITLE
Cover-photo

### PR DESCRIPTION
**Pull request by kvnol**
## Mudanças

- Infinite background scrolling adicionado
- Alterações pequenas no título

---
screenshot

### CODE REVIEW

**Comment by kvnol** [comment]
obs.: aquela crase está errada. <o>

**Comment by femontanha** [comment]
@kvnol I like your idea for infinite scrolling but I don't like the visual changes.
Can I use your idea in my another PullRequest?

**Comment by kvnol** [comment]
Yes, no problems.

**Comment by femontanha** [comment]
Thanks man ... this is my PR with your credits
https://github.com/devnaestrada/devnaestrada.com.br/pull/56

**Pull request closed without merging**
